In [1]:
# Session on Fri 14.11.2025

# Explanation of this session in email from WLP on Thu 13/11/2025 - 
# "This week we’ll continue to look at using tabular data with Pandas. A lot of what we do will be repeating the previous week as a refresher as it’s 
# all key stuff, but we’ll also look at simple joins/merges and some slices based on criteria."

# Last session looked at dataframes - industry standard for Python way of reading tabular data for smaller datasets (not millions of rows)
# It's rare for you to use anything other than pandas (can ready from csv's and excel's like we'll be doing)
# Next year WLP will run a session on Sequel
# 2 weeks ago's session was basic and will be recapped quickly today

#.ipynb (like .csv for csv file)

In [2]:
# Let's use pandas (installing is harder than importing)
# Let's name it pd because we're going to keep using pandas (it's universal to name pandas as pd - keep alises same when wriitng code for other things you import so someone can read your code)
import pandas as pd

# You can read files from your operating system (os)
import os

# We'll be taking from GitHub 
# r means Python read every character as a string exactly as it is

ci_filepath = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv"

cc_filepath = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildCharacteristics.csv"

# From pandas let's read the csv (need . to say to do something)
identifiers = pd.read_csv(ci_filepath)
# You can do header, skiprows etc

characteristics = pd.read_csv(cc_filepath)

In [3]:
# .info is main way to see info
identifiers.info()

# If Dtype comes up 'object' this is basically a string (DOB ought to be a date not string)
characteristics.info()

# .head method shows top few rows 
identifiers.head()
# Standard is 5 but you can go up to 20 if you parse

# Let's make DOB a date type
# Let's not overwrite DOB column we already have - make a new column
# Square brackets mean make a selection
# Let's make a new PersonBirthDate_dt column with as a date type column
# Single brackets makes that thing a string
# strftime - you can Google this (covered last week); capital means 4 digits, lowercase is 2 digits
# Snake case inc _ (used for method/function/variable)
identifiers['PersonBirthDate_dt'] = pd.to_datetime(identifiers['PersonBirthDate'], format="%Y-%m-%d")

identifiers.info()

identifiers['ExpectedPersonBirthDate_dt'] = pd.to_datetime(identifiers['PersonBirthDate'], format="%Y-%m-%d")

# Adding errors means you can tackle if date doesn't fit this style in original dataset
identifiers['PersonDeathDate_dt'] = pd.to_datetime(identifiers['PersonDeathDate'], format="%Y-%m-%d", errors='coerce')

identifiers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               332 non-null    int64
 1   LAchildID                332 non-null    object
 2   UPN                      332 non-null    object
 3   FormerUPN                0 non-null      float64
 4   UPNunknown               0 non-null      float64
 5   PersonBirthDate          332 non-null    object
 6   ExpectedPersonBirthDate  7 non-null      object
 7   GenderCurrent            332 non-null    int64
 8   PersonDeathDate          21 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 23.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  332 non-null    int64
 1   LAchildID   332 non-null    object
 2   Ethnicity   332 non-null    object
dtypes: int64(1), object(2)
memory usage: 7.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               332 non-null    int64
 1   LAchildID                332 non-null    object
 2   UPN                      332 non-null    object
 3   FormerUPN                0 non-null      float64
 4   UPNunknown               0 non-null      float64
 5   PersonBirthDate          332 non-null    object
 6   ExpectedPersonBirthDate  7 non-null      object
 7   GenderCurrent            332 non-null    int64
 8   PersonDeathDate          21 non-null     object
 9   PersonBirthDate_dt       332 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 26.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  332 non-null    int64
 1   LAchildID                   332 non-null    object
 2   UPN                         332 non-null    object
 3   FormerUPN                   0 non-null      float64
 4   UPNunknown                  0 non-null      float64
 5   PersonBirthDate             332 non-null    object
 6   ExpectedPersonBirthDate     7 non-null      object
 7   GenderCurrent               332 non-null    int64
 8   PersonDeathDate             21 non-null     object
 9   PersonBirthDate_dt          332 non-null    datetime64[ns]
 10  ExpectedPersonBirthDate_dt  332 non-null    datetime64[ns]
 11  PersonDeathDate_dt          20 non-null     datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(5)
memory usage: 31.3+ KB

In [4]:
# Let's try and hardcode a dataframe (make tabular data)

# A dictionary has a key with values
# Dictionary is {}; list is []

# Method 1 - dictionary of lists - quick, takes up less time and easier to read
# {key:value}
# Let's add about DataFrame (camel case because there are humps when new word starts) (used for classes)
child_info = pd.DataFrame({'ChildId' : ['id1', 'id2', 'id3', 'id4', 'id5']})
child_info

child_info = pd.DataFrame({'ChildId':['id1', 'id2', 'id3', 'id4', 'id5'],
                           'Age at first contact':[6, 12, 11, 1, 19],
                           'SEX':['M', 'm', 'F', '', 'F'],
                           'Birthday':['01/01/2002', '02/02/2003', '01/01/2000', '03/03/2023', '06/01/2012'],
                           'CP Plan?':['Y', 'n', 'N', 'No', 'yES'],})
child_info

# Method 2 - list of dictionaries 
nhs_numbers = pd.DataFrame([{'ChildId':'id1',
                             'NHS Number':'303'},
                             {'ChildId':'id2',
                              'NHS Number':'3u5029'},
                            {'ChildId':'id3',
                            'NHS Number': 'gqw3',},
                            {'ChildId':'id4',
                            'NHS Number': 'avsgvb',},
                            {'ChildId':'id5',
                            'NHS Number': 'varwvw',},])
nhs_numbers

  ChildId NHS Number
0     id1        303
1     id2     3u5029
2     id3       gqw3
3     id4     avsgvb
4     id5     varwvw

In [5]:
# Calculate ages of children quickly and in a dirty way was done last time - let's change it!
# We need to import a new package called dateutil 
# import dateutil
# But as we only need a specific part of it we can do this
# Delta means difference; it looks at how many who years have passed, accounting for leap years (it includes calendars) - better than subtracting 2 dates in pandas
# BELOW SHOULD NOT BE COMMENTED OUT
# from dateutil.relativedelta import relativedelta

# Read as a non-American date using dayfirst=True
# BELOW SHOULD NOT BE COMMENTED OUT
# child_info['Birthday_dt'] = pd.to_datetime(child_info['Birthday'], dayfirst=True)
# child_info

# relativedelta(pd.to_datetime("today"), row)

# Looks as of today's date, 14/11/2025
# child_info['Age'] = relativedelta(pd.to_datetime("14/11/2025"))

# "today" to future proof
# child_info['Age'] = relativedelta(pd.to_datetime("today"))

# This won't work as last bit is a string(?)
# child_info['Age'] = relativedelta(pd.to_datetime("today"), child_info['Birthday_dt'])

# So let's do apply and write a function so we can do relativedelta to it (relativedelta works in rows)
# lambdas are used once - we don't need to name that function
# BELOW SHOULD NOT BE COMMENTED OUT
# child_info['Age'] = child_info['Birthday_dt'].apply(lambda row: relativedelta(pd.to_datetime("today"), row).years)
# BELOW SHOULD NOT BE COMMENTED OUT
# child_info()


# Above was confusing - correct from WLP:
from dateutil.relativedelta import relativedelta

child_info['Birthday_dt'] = pd.to_datetime(child_info['Birthday'], dayfirst=True)

# relativedelta(pd.to_datetime("today"), row)

child_info['Age'] = child_info['Birthday_dt'].apply(lambda row: relativedelta(pd.to_datetime("today"), row).years)

child_info

  ChildId  Age at first contact SEX    Birthday CP Plan? Birthday_dt  Age
0     id1                     6   M  01/01/2002        Y  2002-01-01   23
1     id2                    12   m  02/02/2003        n  2003-02-02   22
2     id3                    11   F  01/01/2000        N  2000-01-01   25
3     id4                     1      03/03/2023       No  2023-03-03    2
4     id5                    19   F  06/01/2012      yES  2012-01-06   13

In [6]:
# My exercise to add in a new Age column - my try below using CoPilot and notes from this session to help me

# child_info.info()
# child_info['Age'] = pd.to_numeric(child_info['Age'], errors='coerce')
# child_info.info()

In [7]:
# x is the name of the variable below
# Age is given in years due to .years at the end
identifiers['Age'] = identifiers['PersonBirthDate_dt'].apply(lambda x: relativedelta(pd.to_datetime('today'), x).years)
identifiers

,Unnamed: 0,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate,PersonBirthDate_dt,ExpectedPersonBirthDate_dt,PersonDeathDate_dt,Age
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN,2019-12-06,2019-12-06,NaT,5
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN,2011-04-27,2011-04-27,NaT,14
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN,2017-06-06,2017-06-06,NaT,8
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN,2014-10-03,2014-10-03,NaT,11
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN,2019-09-25,2019-09-25,NaT,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,327,RND000112711501,A465246916125,NaN,NaN,2010-07-07,NaN,2,NaN,2010-07-07,2010-07-07,NaT,15
328,328,RND000513120794,A540014111973,NaN,NaN,2018-08-14,NaN,2,NaN,2018-08-14,2018-08-14,NaT,7
329,329,RND000541643134,A549582689058,NaN,NaN,2021-12-09,NaN,51,NaN,2021-12-09,2021-12-09,NaT,3
330,330,RND000404939452,A889492349196,NaN,NaN,2013-07-23,NaN,2,NaN,2013-07-23,2013-07-23,NaT,12
331,331,RND000589802835,A877624860226,NaN,NaN,2021-10-25,NaN,9,NaN,2021-10-25,2021-10-25,NaT,4

In [8]:
# Let's try reading in an Excel (file formats are different plus can have multiple sheets so interesting to look at here!)

import openpyxl

filepath = r"https://github.com/data-to-insight/ERN-sessions/raw/main/data/small%20excel.xlsx"

# excel not csv
df = pd.read_excel(filepath)

# ModuleNotFoundError comes up

# Put importopenpyxl but error stillthere so we need to install something in terminal below
# pip install openpyxl
# Be careful what you install esp if you have Python on your laptop!
# Now the code above in this section runs!
# Standard thing it'll do is read the first sheet, however we can specify which sheet name we want to read in e.g. one called Child extras
df = pd.read_excel(filepath, sheet_name='Child extras')
# Below means import every sheet
# type(df) will be dict (i.e dictionary) for None
df_dict = pd.read_excel(filepath, sheet_name=None)
# df_dict['Child Data']
# Unsure of next 3 lines
# df_dict[keys]
# df_dict[values]
# df_dict[items]

# Correct one by WLP below
import openpyxl

filepath = r"https://github.com/data-to-insight/ERN-sessions/raw/main/data/small%20excel.xlsx"

df_dict = pd.read_excel(filepath, sheet_name=None)

In [9]:
print(child_info.columns)
# See columns from nhs numbers so we can see which columns come up in this and child info above
print(nhs_numbers.columns)
# ChildId column is the same so let's link both tables based on this
# Join using merge in pandas (left to right but concat is when you add to the bottom) but can be called join outside pandas
# Tell them which tables we're joining, what columns we're joining
# Inner, Outer, Left, and Right are main joins we use
# Inner join takes something in both tables; outer joins all the data and we don't care what's in each; 
# Left takes stuff from RHS table if it corresponds to LHS table but don't drop from LHS table; right is similar except keep RHS and add on stuff from LHS
# As we have a 1-1 match we could do any join but let's do a left join
# ERROR ON LINE BELOW??
child_info = pd.merge(child_info, nhs_numbers, left_on='ChildId', right_on='ChildId', how='left')
child_info()

Index(['ChildId', 'Age at first contact', 'SEX', 'Birthday', 'CP Plan?',
       'Birthday_dt', 'Age'],
      dtype='object')
Index(['ChildId', 'NHS Number'], dtype='object')

TypeError: 'DataFrame' object is not callable

In [ ]:
# This is a pandas merge but a bit longer to write
# identifiers = left.merge(right)

# Alternative below
# identifiers = identifiers.merge

# suffixes - If a column exists in both LHS and RHS table then you can denote LAchildID from LHS and RHS tables differently
# identifiers = identifiers.merge(characteristics, on='LAchildID', how='left', suffixes=['_ident', '_char'])
# identifiers

# You can merge on LAChildID and another column
identifiers = identifiers.merge(characteristics, on=['LAchildID', 'Unnamed: 0'], how='left')
identifiers
# If it doesn't work, you may need to click 'Refresh' to forget everything done so far and then click 'Run All'

,Unnamed: 0_ident,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate,PersonBirthDate_dt,ExpectedPersonBirthDate_dt,PersonDeathDate_dt,Age,Unnamed: 0_char,Ethnicity_ident,Unnamed: 0,Ethnicity_char,Ethnicity
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN,2019-12-06,2019-12-06,NaT,5,0,WIRT,0,WIRT,WIRT
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN,2011-04-27,2011-04-27,NaT,14,1,WROM,1,WROM,WROM
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN,2017-06-06,2017-06-06,NaT,8,2,AOTH,2,AOTH,AOTH
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN,2014-10-03,2014-10-03,NaT,11,3,MWBC,3,MWBC,MWBC
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN,2019-09-25,2019-09-25,NaT,6,4,APKN,4,APKN,APKN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,327,RND000112711501,A465246916125,NaN,NaN,2010-07-07,NaN,2,NaN,2010-07-07,2010-07-07,NaT,15,327,WOTH,327,WOTH,WOTH
328,328,RND000513120794,A540014111973,NaN,NaN,2018-08-14,NaN,2,NaN,2018-08-14,2018-08-14,NaT,7,328,WROM,328,WROM,WROM
329,329,RND000541643134,A549582689058,NaN,NaN,2021-12-09,NaN,51,NaN,2021-12-09,2021-12-09,NaT,3,329,BCRB,329,BCRB,BCRB
330,330,RND000404939452,A889492349196,NaN,NaN,2013-07-23,NaN,2,NaN,2013-07-23,2013-07-23,NaT,12,330,AIND,330,AIND,AIND
331,331,RND000589802835,A877624860226,NaN,NaN,2021-10-25,NaN,9,NaN,2021-10-25,2021-10-25,NaT,4,331,WBRI,331,WBRI,WBRI

In [12]:
# Merge 3 tables

df_dict.keys()
 
# Better to merge separately than join all 3 tables in 1 line! 
df = df_dict['Child Data'].merge(df_dict['Child extras'], on='ChildID', how='left')
df = df.merge(df_dict['Sheet3'], on='Assessment Code', how='left')
 
df

  ChildID Sex        DOB EHCP issued  Assessment Code Assessment Outcome
0     id1   M 2014-12-05           N                1                  Y
1     id6   m 2016-01-06           n                5                  y
2     id4   m 2013-11-09           Y                3                  N
3     id3   F 2022-12-24           Y                4                  n
4     id5   F 2020-01-15         NaN                2                  N
5     id7   f 2022-09-17           y                6                  N

In [ ]:
# < means less than
# > means greater than
# Is the value in 1 column <, > or = to another?
# < and > works for numbers and dates

# == means equals
# == means works for strings, numbers and dates

# ~ means not
# >= or <= greater/less than or equal to

# To join up logical conditions you can use 2 symbols below
# & and 
# | or (pipe)

# .isna() or .notna() - return rows where there is or not a null
# . isin() - if returns values in row when it contains something
# .str.contains() - string contains something