In [60]:
# Session on Fri 28.11.2025

# Notes from email WLP sent on Thu 27/11/2025- 

# This weeks Python session looks at plotting. We’ll be using Plotly as it’s pretty whizzy for being pretty low code, and it’s my go to for my work, 
# but most plotting libraries work really similarly so if you get used to one, it’s not hard to learn another. In many cases you’ll find you need to 
# know more than one plotting library anyway based on what plots you need to make and the customizability you need for each one.

In [61]:
import pandas as pd

# variable is url
url = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/1980%202023%20average%20house%20prices.csv"

# Use read_csv function from pandas
df = pd.read_csv(url)

df.head()

,Name,Period,House price index All property types,Average price All property types,Percentage change (monthly) All property types,Percentage change (yearly) All property types
0,United Kingdom,1980-01,10.11,19273,3.94,28.59
1,United Kingdom,1980-02,10.11,19273,3.94,28.59
2,United Kingdom,1980-03,10.11,19273,3.94,28.59
3,United Kingdom,1980-04,10.51,20044,4.00,24.15
4,United Kingdom,1980-05,10.51,20044,4.00,24.15

In [62]:
df.info()
# This helps us get a gist of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523 entries, 0 to 522
Data columns (total 6 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Name                                            523 non-null    object
 1   Period                                          523 non-null    object
 2   House price index All property types            523 non-null    float64
 3   Average price All property types                523 non-null    int64
 4   Percentage change (monthly) All property types  523 non-null    float64
 5   Percentage change (yearly) All property types   523 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 24.6+ KB

In [63]:
# Let's make all columns lowercase as we see uppercase halfway through if we just do df.info() - easier to work with that way
# df.columns gives us column headings
# df.columns = str.lower
# It'll take every bit of list series and make it lowercase then overwrite the original column names
df.columns = map(str.lower, df.columns)

df.info()
# This helps us get a gist of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523 entries, 0 to 522
Data columns (total 6 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   name                                            523 non-null    object
 1   period                                          523 non-null    object
 2   house price index all property types            523 non-null    float64
 3   average price all property types                523 non-null    int64
 4   percentage change (monthly) all property types  523 non-null    float64
 5   percentage change (yearly) all property types   523 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 24.6+ KB

In [64]:
# Make 'period' column into datetime

# coerce gives errors as NA rather than ignorning them
df["period_dt"] = pd.to_datetime(df['period'], format="%Y-%m", errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 523 entries, 0 to 522
Data columns (total 7 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   name                                            523 non-null    object
 1   period                                          523 non-null    object
 2   house price index all property types            523 non-null    float64
 3   average price all property types                523 non-null    int64
 4   percentage change (monthly) all property types  523 non-null    float64
 5   percentage change (yearly) all property types   523 non-null    float64
 6   period_dt                                       523 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(2)
memory usage: 28.7+ KB

In [65]:
# plotly express - allows you to make a plot quickly and easily; this is a graph objects - it's a submodule of graph objects module
# graph objects - really powerful but slightly long winded making it e.g. moving titles around, orders, colours etc

# px is short for plot(ly) ex(press)
import plotly.express as px

# Scatterplot is good to show time series data
price_over_time = px.scatter(df,
                             x="period_dt",
                             y="average price all property types")

price_over_time.show()

# You can zoom in/out of certain bits (hover on RHS of plot)
# If you double click you can go back to the centre
# Lasso select - allows you to make a selection of data in plot itself and investigate it further and change a different plot - advanced stuff!

In [66]:
# Let's make a title and x-axis and y-axis names, plus fit a trend line to see if there's a trend/relationship between x and y
# Hit control + j to open your terminal, or click 3 lines on top LHS and get terminal from there
# In terimanl type pip install statsmodels then click x in popup to close it down

import statsmodels

# We have to use period_dt because it won't work if we use period (which isn't in the format - time - that scatter plot needs it to be)
# New visual where ols will look at a trend line
# Labels bit - LHS gives us original name and RHS of : gives us what we want it to say instead
# ols is a type of trend line? There are others out there?
# ols - order of least squares gives a line closest to the points
price_over_time_ols = px.scatter(df, 
                                 x='period_dt',
                                 y='average price all property types',
                                 title="Change in average property price (Monthly/£)",
                                 labels={'period_dt':"Time period",
                                         'average price all property types':"House Prices"},
                                 trendline="ols")

price_over_time_ols.show()

In [67]:
# Let's look at some data more related to us now

# This is fake CIN data
filepath = r'https://raw.githubusercontent.com/data-to-insight/D2I-Jupyter-Notebook-Tools/main/ml-data%20science%20tutorials/data/CINdetails.csv'

cin = pd.read_csv(filepath)

cin.info()

# CINdetailsID isn't in CIN return but is used in validator that D2i invented

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        101 non-null    int64
 1   LAchildID         101 non-null    object
 2   CINdetailsID      101 non-null    int64
 3   CINreferralDate   101 non-null    object
 4   ReferralSource    101 non-null    object
 5   PrimaryNeedCode   101 non-null    object
 6   CINclosureDate    63 non-null     object
 7   ReasonForClosure  63 non-null     object
 8   DateOfInitialCPC  85 non-null     object
 9   ReferralNFA       101 non-null    bool
dtypes: bool(1), int64(2), object(7)
memory usage: 7.3+ KB

In [68]:
# Let's get rid of columns we don't need
# The following won't work 
# cin.drop("Unnamed: 0")

# There are 2 axes - 0 is rows and 1 is columns
# Default is to remove rows
# This won't work either
# cin.drop("Unnamed: 0", axis=1)

# This will work
cin.drop("Unnamed: 0", axis=1, inplace=True)

cin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LAchildID         101 non-null    object
 1   CINdetailsID      101 non-null    int64
 2   CINreferralDate   101 non-null    object
 3   ReferralSource    101 non-null    object
 4   PrimaryNeedCode   101 non-null    object
 5   CINclosureDate    63 non-null     object
 6   ReasonForClosure  63 non-null     object
 7   DateOfInitialCPC  85 non-null     object
 8   ReferralNFA       101 non-null    bool
dtypes: bool(1), int64(1), object(7)
memory usage: 6.5+ KB

In [69]:
# Let's look at making a plot
# A lot are called histograms (continuous data) but are bar charts (categorical data)

# primary need code - pnc
pnc_bar = px.histogram(cin,
                       x='PrimaryNeedCode')

pnc_bar.show()

# Bars are not joined

In [70]:
# Let's do in alphabetical order the primary need code

# The following code from WLP doesn't work (my codespace crashed while he did this bit lol) - it works if you click 'Run All' at the top!

import plotly.graph_objects as go

pnc_bar = px.histogram(cin,
                       x='PrimaryNeedCode')

pnc_bar.update_xaxes(categoryorder='category ascending')

pnc_bar.show()

In [71]:
# Doing something with colour - use American version of spelling

# This code from WLP doesn't work either - it works if you click 'Run All' at the top!

import plotly.graph_objects as go

pnc_bar = px.histogram(cin,
                       x='PrimaryNeedCode',
                       color='ReferralSource')

pnc_bar.update_xaxes(categoryorder='category ascending')

pnc_bar.show()

In [72]:
# Exercise - Add a new column called CPCTimeliness (a measure of time of each CIN plan between referral and initial child protection conference i.e. initial cpc)
# ['CINreferralDate], ['DateOfInitialCPC'] <-- as an integer make a new column with these times in
# New column ['CPCTimeliness']

# My attempt and it seemed to have worked!
# cin['DateOfInitialCPC'] = pd.to_datetime(cin['DateOfInitialCPC'])
# cin['CINreferralDate'] = pd.to_datetime(cin['CINreferralDate'])
# cin['CPCTimeliness'] = cin['DateOfInitialCPC'] - cin['CINreferralDate']
# cin.info()
# cin.head()

# WLP's method to do it
# Convert to date first
cin['CINreferralDate_dt'] = pd.to_datetime(cin['CINreferralDate'], format="%d/%m/%Y")
cin['DateOfInitialCPC_dt'] = pd.to_datetime(cin['DateOfInitialCPC'], format="%d/%m/%Y")

cin['CPCTimeliness'] = cin['DateOfInitialCPC_dt'] - cin['CINreferralDate_dt']

# I think we're moving the word 'days' at the end?
cin['CPCTimeliness'] = cin['CPCTimeliness']/pd.Timedelta(1, 'd')

cin




# Wrong
# cin['CINreferralDate_dt'] = pd.to_datetime(cin['CINreferralDate'], format="%d/%m/%Y")
# cin['DateOfInitialCPC_dt'] = pd.to_datetime(cin['DateOfInitialCPC'], format="%d/%m/%Y")

# cin['CPCTimeliness'] = cin['DateOfInitialCPC_dt'] - cin[CINreferralDate_dt]

# cin['CPCTimeliness'] = cin['CPCTimeliness']/pd.Timedelta(1, 'd')

# cin

,LAchildID,CINdetailsID,CINreferralDate,ReferralSource,PrimaryNeedCode,CINclosureDate,ReasonForClosure,DateOfInitialCPC,ReferralNFA,CINreferralDate_dt,DateOfInitialCPC_dt,CPCTimeliness
0,RND000215205141,1,13/07/2020,4,N6,11/06/2021,RC2,29/09/2020,False,2020-07-13,2020-09-29,78.0
1,RND000824303014,1,25/10/2013,6,N8,01/01/2014,RC1,13/12/2013,False,2013-10-25,2013-12-13,49.0
2,RND000824303014,2,22/10/2017,3A,N9,NaN,NaN,05/11/2017,False,2017-10-22,2017-11-05,14.0
3,RND000750143123,1,14/01/2020,2A,N4,16/06/2020,RC4,20/03/2020,False,2020-01-14,2020-03-20,66.0
4,RND000750143123,2,07/02/2022,9,N9,NaN,NaN,01/05/2022,False,2022-02-07,2022-05-01,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...
96,RND000114887428,1,23/11/2010,5B,N4,18/08/2012,RC7,19/12/2010,False,2010-11-23,2010-12-19,26.0
97,RND000031122698,1,12/08/2019,1A,N9,17/09/2021,RC7,05/10/2019,False,2019-08-12,2019-10-05,54.0
98,RND000875696504,1,18/05/2018,6,N6,27/05/2018,RC5,NaN,False,2018-05-18,NaT,NaN
99,RND000808364555,1,22/07/2018,3F,N9,05/06/2020,RC6,28/08/2018,False,2018-07-22,2018-08-28,37.0
100,RND000808364555,2,05/04/2022,3B,N9,24/04/2022,RC3,22/04/2022,False,2022-04-05,2022-04-22,17.0

In [73]:
# Let's make a histogram

timeliness_hist = px.histogram(cin,
                               x='CPCTimeliness',
                               title='Time between referral and ICPC')

timeliness_hist.show()
# Bars (bins) are next to each other meaning we're seeing a histogram

In [74]:
# Bins are quite big - let's make 20 bins (breaking down to 5 days each)

timeliness_hist = px.histogram(cin,
                               x='CPCTimeliness',
                               title='Time between referral and ICPC',
                               nbins=20)

timeliness_hist.show()

In [75]:
# How else can we see breakdowns?
# Box plots allow you to see spread of the data visualising it - WLP likes these as they're powerful - e.g. quartile ranges, outliers etc

# Data is on y-axis not x-axis anymore since it's a box plot
timeliness_box = px.box(cin,
                        y='CPCTimeliness')

timeliness_box.show()
# Most people are between quartiles; median is 46 days; spread goes from 0 to 87 days
# Nice to see ranges our data is in

In [76]:
# Let's compare 

timeliness_box = px.box(cin,
                        y='CPCTimeliness',
                        color='PrimaryNeedCode')

timeliness_box.show()

# Shows all breakdowns by primary need code; average is in middle of the boxes; for N2 and N0 the median is close but some N2s take a long or short time to see them
# Most N6s are seen very late; e.g. abuse seen quicker than neglect 
# We could look at referral source e.g. is police looked at slower/quicker than others?

In [ ]:
# Let's make a marginal scatter

# Use CINreferralDate_dt than CINreferralDate otherwise x-axis will be messed up lol
marginal_scatter = px.scatter(cin, 
                              x='CINreferralDate_dt',
                              y='CPCTimeliness')

marginal_scatter.show()
# We can't tell a lot although maybe we had more data recently than in 2005? Can't see properly though

In [78]:
marginal_scatter = px.scatter(cin, 
                              x='CINreferralDate_dt',
                              y='CPCTimeliness',
                              marginal_y='violin',
                              marginal_x='violin')

marginal_scatter.show()
# Violin is thicker - more in 2020 than 2005 region

In [79]:
marginal_scatter = px.scatter(cin, 
                              x='CINreferralDate_dt',
                              y='CPCTimeliness',
                              marginal_y='violin',
                              marginal_x='rug')

marginal_scatter.show()

In [82]:
# Facet plots allow you to break down plots on rows and columns based on other data
# Link - https://plotly.com/python/facet-plots/
# E.g. as bill increases, tip increases for waitors, however facet plots allow you to see scatterplot for female waitresses vs male waitors separately (next to each other)
# Helps you compare same thing for different things e.g. are we having more referrals in one quarter than another?

# This is the gapminder dataset which comes with plotly as a sample dataset
# data is every 5 years data for a bunch of countries over time
df = px.data.gapminder()
df

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [83]:
# Let's make a scatterplot
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp')
fig.show()
# We can't make much sense - can't see country/continent/year
# We may like to make a logarithmic scale as data is all bunched up

In [84]:
# x axis is easier to read with logarithmic

fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True)
fig.show()

In [87]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent')
fig.show()
# As GDP per capita increases, so does life expectancy - there seems to be a relationship, but we can't see countries and what years

In [90]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country')
fig.show()

# Rwanda at bottom and Kuwait at top end

In [ ]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year')
fig.show()

# Drag across to follow one country/continent around over time

In [92]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year',
                 size='pop')
fig.show()

# Points is related to size of population

In [93]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year',
                 size='pop',
                 size_max=45)
fig.show()

# Set a maximum so China doesn't overempower the other points

In [94]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year',
                 size='pop',
                 size_max=45,
                 facet_col='continent')
fig.show()

In [95]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year',
                 size='pop',
                 size_max=45,
                 facet_col='continent',
                 range_y=[0,90])
fig.show()

In [98]:
fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year',
                 size='pop',
                 size_max=45,
                 facet_col='continent',
                 range_y=[0,df['lifeExp',max()]])
fig.show()

TypeError: max expected at least 1 argument, got 0

In [99]:
# +5 bit allows you to also see Japan (otherwise we're right up to the wire lol)

fig = px.scatter(df,
                 x='gdpPercap',
                 y='lifeExp',
                 log_x=True,
                 color='continent',
                 hover_name='country',
                 animation_frame='year',
                 size='pop',
                 size_max=45,
                 facet_col='continent',
                 range_y=[0,df['lifeExp',max() + 5]])
fig.show()

TypeError: max expected at least 1 argument, got 0

In [ ]:
# Next session we'll be looking at coding than data science side of things
# Automation, writing little bits of code which makes you do a lot
# We're at the end of the basics now - abstract but cool stuff coming up in next 2 weeks!